site_name: PatchMyPath

nav:
  - PatchMyPath:
    - Welcome: index.md
    - Getting started: getting-started.md
    - Customization: customization.md
  - Configuration:
    - Base Configuration: config/root.md
    - Install Objects: config/install.md
  - Tutorials:
    - Duplicating Vanilla Installs: tutorials/duplicating.md

repo_name: justalemon/PatchMyPath
repo_url: https://github.com/justalemon/PatchMyPath

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details

theme:
  name: material
  palette:
    primary: red
    accent: red
  feature:
    tabs: true

extra:
  social:
    - type: discord
      link: https://discord.gg/Cf6sspj
    - type: github
      link: https://github.com/justalemon
    - type: steam
      link: https://steamcommunity.com/profiles/76561198118215221/
    - type: twitter
      link: https://twitter.com/justlemonades
    - type: twitch
      link: https://www.twitch.tv/justlemoncl
    - type: gamepad
      link: https://www.gta5-mods.com/users/justalemon
