name: Documentation

on:
  push:
    paths:
      - "**.md"
      - "**.png"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout on Current Commit
        uses: actions/checkout@master
      - name: Build with mkdocs and mkdocs-material
        uses: FullDiveCollective/MarkdownMaterial@master
        with:
          cname: "patchmypath.justalemon.ml"
      - name: Deploy to GitHub Pages
        uses: FullDiveCollective/DeployToBranch@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
