name: Visual Studio

on:
  push:
    paths:
      - "**.cs"
      - "**.sln"
      - "**.config"
      - "**.csproj"
      - "**.settings"
      - "**.json"
      - "**.resx"
      - ".github/workflows/visualstudio.yml"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout on Current Commit
        uses: actions/checkout@master
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Install the NuGet packages
        run: nuget restore PatchMyPath.sln
      - name: Build with msbuild.exe
        run: msbuild PatchMyPath.sln /t:Build /p:Configuration=Release
      - name: Package Artifacts
        working-directory: bin\Release
        run: 7z a PatchMyPath.7z *
      - uses: actions/upload-artifact@v1
        with:
          name: PatchMyPath.7z
          path: PatchMyPath.7z
